name: Export HLS Playlists

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  export-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Run PHP Script
      run: |
        php updatePlaylist.php > exported_playlists.m3u
        echo "Exported playlist saved to exported_playlists.m3u"

    - name: Commit and Push File
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        mv exported_playlists.m3u path/to/destination/exported_playlists.m3u
        git add path/to/destination/exported_playlists.m3u
        git commit -m "Add or update exported playlists"
        git push
