name: Generate and Commit M3U File

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Run PHP Script
      run: php extract-token.php

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add exported_playlists.m3u
        git commit -m "Generate exported_playlists.m3u"
        git push origin main
